/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtattoo.demo.app;

import com.jtattoo.demo.images.ImageHelper;
import com.jtattoo.demo.utils.GridBagHelper;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;

/**
 *
 * @author Sunil
 */
public class welcome extends javax.swing.JPanel implements ActionListener{

    private JPanel widgetPanel = null;
    private JScrollPane tablePanel = null;
    private JSplitPane splitPane = null;
    private JComboBox addressCombo = null;
    private JScrollPane tableScrollPane = null;
    public JTextField userid=null;
    public JPasswordField password = null;
    public JButton login = null;
    public welcome() 
    {
        setName("Start");
        initComponents();
           initModel();
        initControls();
        initListeners();
        ImageIcon icon2 = new ImageIcon(ImageHelper.loadImage("s-1.jpg").getImage());
        jLabel2.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        jLabel2.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) 
    {
          
     }
    
       private void initModel()
       {
           
       }
       
        private void initControls()
        {
        widgetPanel = createWidgetPanel();
//        tablePanel = createTablePanel();
        splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, true, widgetPanel, tablePanel);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(320);
        add(splitPane, BorderLayout.CENTER);
        } 
          private void initListeners()
          {
              
          }
            private JPanel createWidgetPanel() {
            JPanel panel = new JPanel(new BorderLayout());
             panel.add(createFormPanel(), BorderLayout.CENTER);
        
            panel.add(createButtonPanel(), BorderLayout.EAST);
        
           return panel;
    
         } 
             private JScrollPane createFormPanel() 
    {
        addressCombo = new JComboBox(new String[]{"Mr.", "Mrs.", "Sir", "Lady", "Herr", "Frau"});
        addressCombo.setToolTipText("Select salutation!");
        userid = new JTextField();
        password= new JPasswordField();
        //oldpass=new JPasswordField();
      
          
//        streetField = new JTextField();
//        cityField = new JTextField();
//        cityField.setToolTipText("<html>This is a long tool tip (also known as bubble help)<br/>for the city text field.<br/><br/>Here comes some more useless text.");

        //    JPanel radioPanel = new JPanel(new BorderLayout());
        //  radioPanel.setBorder(JTBorderFactory.createTitleBorder("favorite color"));
//        redButton = new JRadioButton("red");
//        greenButton = new JRadioButton("green");
//        blueButton = new JRadioButton("blue");
//        radioPanel.add(redButton, BorderLayout.NORTH);
//        radioPanel.add(greenButton, BorderLayout.CENTER);
//        radioPanel.add(blueButton, BorderLayout.SOUTH);
//        buttonGroup = new ButtonGroup();
//        buttonGroup.add(redButton);
//        buttonGroup.add(greenButton);
//        buttonGroup.add(blueButton);
//        redButton.setSelected(true);

//        JPanel checkPanel = new JPanel(new BorderLayout());
//        checkPanel.setBorder(JTBorderFactory.createTitleBorder("favorite food"));
//        bananaButton = new JCheckBox("bananas");
//        burgerButton = new JCheckBox("hamburgers");
//        icecreamButton = new JCheckBox("icecream");
//        checkPanel.add(bananaButton, BorderLayout.NORTH);
//        checkPanel.add(burgerButton, BorderLayout.CENTER);
//        checkPanel.add(icecreamButton, BorderLayout.SOUTH);

        JPanel panel = new JPanel(new GridBagLayout());
        //panel.setOpaque(false);
        JPanel topDistPanel = new JPanel();
        JPanel bottomDistPanel = new JPanel();
        GridBagHelper.addComponent(panel, topDistPanel, 0, 0, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.NORTHWEST);

        //GridBagHelper.addComponent(panel, new JLabel("User Login Name: "+enrll), 0, 1, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
       // GridBagHelper.addComponent(panel, addressCombo, 1, 1, 1, 1, 0, 0, 0.3, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.NORTHWEST);
        GridBagHelper.addComponent(panel, new JPanel(), 2, 1, 1, 1, 0, 0, 0.7, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
       
       // GridBagHelper.addComponent(panel, new JLabel("Today Data Usage:"+datause+" MB"), 0, 2, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
       // GridBagHelper.addComponent(panel, firstNameField, 1, 2, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
         //GridBagHelper.addComponent(panel, new JLabel("IP_Address Of Access Pcs: "+ip), 0, 3, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
//        GridBagHelper.addComponent(panel, lastNameField, 1, 3, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
         
          GridBagHelper.addComponent(panel, new JLabel("User ID"), 0, 5, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
        GridBagHelper.addComponent(panel,userid , 1, 5, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);

         
         GridBagHelper.addComponent(panel, new JLabel("PassWord:"), 0, 6, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
         GridBagHelper.addComponent(panel, password, 1, 6, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
         
         //GridBagHelper.addComponent(panel, new JLabel("Enter Conform PassWord:"), 0, 7, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
         //GridBagHelper.addComponent(panel, renewpass, 1, 7, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
         
          //GridBagHelper.addComponent(panel, new JLabel("Enter , 0, 7, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.NONE, GridBagConstraints.WEST);
         //GridBagHelper.addComponent(panel, renewpass, 1, 8, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
         //GridBagHelper.addComponent(panel, chgepass, 1, 8, 3, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST);
       // GridBagHelper.addComponent(panel, radioPanel, 0, 6, 2, 1, 0, 0, 0.0, 0.0, GridBagConstraints.BOTH, GridBagConstraints.WEST);
        //GridBagHelper.addComponent(panel, checkPanel, 2, 6, 1, 1, 0, 0, 0.0, 0.0, GridBagConstraints.BOTH, GridBagConstraints.WEST);

        GridBagHelper.addComponent(panel, bottomDistPanel, 0, 10, 1, 1, 0, 0, 0.0, 1.0, GridBagConstraints.VERTICAL, GridBagConstraints.NORTHWEST);

        JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
        return scrollPane;
    }
    private JScrollPane createButtonPanel() 
    {
          JPanel panel = new JPanel(new GridBagLayout());
          login = new JButton("Login");
          login.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) 
            {
                System.out.println("user login successfully");
            }
        });
          GridBagHelper.setMinRowHeight(panel, 0, 8);
        GridBagHelper.setMinColWidth(panel, 0, 100);
        GridBagHelper.addComponent(panel, login, 5, 7, 1, 1, 0, 0, 1.0, 0.0, GridBagConstraints.HORIZONTAL, GridBagConstraints.LAST_LINE_END);
         
          JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
        return scrollPane;
           }

}
