/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jtattoo.demo.app;

import connection.constants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Liza
 */
// for layout to display a permission
public class pendriveaccess extends javax.swing.JPanel  implements ActionListener{

    /**
     * Creates new form pendriveaccess
     */
    String setperm;
     String str2;
      constants connect = new constants();
      Connection con=null;
      String lab,permission1,pc1,illegal1;
      
    
    public pendriveaccess() {
        setName("Permission");
        initComponents();
        setpermission.addActionListener(this);
       // pcname.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        permission = new javax.swing.JComboBox();
        labid = new javax.swing.JComboBox();
        setpermission = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        illegal = new javax.swing.JComboBox();

        permission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionActionPerformed(evt);
            }
        });

        labid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "103", "104", "105" }));

        setpermission.setText("Set permission");
        setpermission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setpermissionActionPerformed(evt);
            }
        });

        jLabel1.setText("Lab ID");

        jLabel2.setText("permission_pendrive");

        jLabel3.setText("Permission_Illegal");

        illegal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        illegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illegalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setpermission)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labid, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permission, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(illegal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(permission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(illegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(setpermission)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setpermissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setpermissionActionPerformed
   Statement st =null;
      lab =labid.getSelectedItem().toString();
   permission1=permission.getSelectedItem().toString();
   illegal1=illegal.getSelectedItem().toString();
        System.out.println("liza"+permission1);
        System.out.println("mihir"+illegal1);
  // pc1=pcname.getText();
        try{
       Class.forName("com.mysql.jdbc.Driver");
       con = DriverManager.getConnection(connect.url, connect.userName, connect.Password);
       String query = "update student_work_detail set PERMISSION= ?,PERMISSION_ILLEGAL=? where LAB_ID=?";
           
        PreparedStatement insert = con.prepareStatement(query);
                        
                       
                        insert.setString(1, permission1);
                        insert.setString(2, illegal1);
                         insert.setString(3, lab);
                        //insert.setString(3, pc1);
                        
             int rs1 = insert.executeUpdate();
                        //System.out.println("affected rows:" + rs1);
                        System.out.println("Data inserted successfully");
       
   }
       
   catch(Exception ex)
   {
       ex.printStackTrace();
   }
           
  
    }//GEN-LAST:event_setpermissionActionPerformed

    private void permissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permissionActionPerformed

    private void illegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illegalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_illegalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox illegal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox labid;
    private javax.swing.JComboBox permission;
    private javax.swing.JButton setpermission;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
    }


}
